### ISSUE TITLE
Create TransportScreen

### ISSUE THREAD

**Issue by teotigraphix** [teotigraphix/Touch4Bitwig#3]
Functionality;

**Transport controls**
- Audio engine toggle
- Stop
- Play
- Record
- Automation

**Display**
- BPM
- Bar/Steps
- Time/Position
- Time signature

**Comment by teotigraphix** [comment]
Created a bar for the transport that can be used anywhere, this still need a design for the "Screen" with position and tempo change, tap tempo etc.

**Comment by SoundGoddess** [comment]
Well we could just leave out screen rotation for the first iteration, save the portrait view for 0.2 or something?

Anyway I drew up a design idea here ~ 
![pagmcnr](https://cloud.githubusercontent.com/assets/6850007/9432616/7667457c-49da-11e5-84cd-d96625fff02d.jpg)

**Comment by teotigraphix** [comment]
BPM needs SpinnerLists

**Comment by teotigraphix** [comment]
Calculate time from bars to ticks. <- Need major calculation, actually need API from Bitwig.

**Comment by teotigraphix** [comment]
Impl (minimal) but done, add more feature requests for more functionality.
